final_pro/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace final_pro.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {


        }
        public DbSet<Postbook> Books { get; set; }
    }
}

final_pro/Models/ErrorViewModel.cs
using System;

namespace final_pro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

final_pro/Models/Postbook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace final_pro.Models
{
    public class Postbook
    {
        [Key]
        public string title { get; set; }
        public string author { get; set; }
        public int ISBN { get; set; }
        public int number { get; set; }
        public int year { get; set; }
    }
}

final_pro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using final_pro.Models;

namespace final_pro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

final_pro/Controllers/PostbooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using final_pro.Models;

namespace final_pro.Controllers
{
    public class PostbooksController : Controller
    {
        private readonly AppDbContext _context;

        public PostbooksController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Postbooks
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Books.ToListAsync());
        //}

        // GET: Postbooks/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postbook = await _context.Books
                .FirstOrDefaultAsync(m => m.title == id);
            if (postbook == null)
            {
                return NotFound();
            }

            return View(postbook);
        }
        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "title")
            {
                return View(_context.Books.Where(x => x.title.StartsWith(search) || search == null).ToList());
            }
            else 
            {
                return View(_context.Books.Where(x => x.author.StartsWith(search)|| search == null).ToList());
            }
            
        }

        // GET: Postbooks/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Search()
        {
            return View();
        }

        // POST: Postbooks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("title,author,ISBN,number,year")] Postbook postbook)
        {
            if (ModelState.IsValid)
            {
                _context.Add(postbook);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(postbook);
        }

        // GET: Postbooks/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postbook = await _context.Books.FindAsync(id);
            if (postbook == null)
            {
                return NotFound();
            }
            return View(postbook);
        }

        // POST: Postbooks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("title,author,ISBN,number,year")] Postbook postbook)
        {
            if (id != postbook.title)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(postbook);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostbookExists(postbook.title))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(postbook);
        }

        // GET: Postbooks/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postbook = await _context.Books
                .FirstOrDefaultAsync(m => m.title == id);
            if (postbook == null)
            {
                return NotFound();
            }

            return View(postbook);
        }

        // POST: Postbooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var postbook = await _context.Books.FindAsync(id);
            _context.Books.Remove(postbook);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostbookExists(string id)
        {
            return _context.Books.Any(e => e.title == id);
        }
    }
}

final_pro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

final_pro/Views/Postbooks/Create.cshtml
@model final_pro.Models.Postbook

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Postbook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="author" class="control-label"></label>
                <input asp-for="author" class="form-control" />
                <span asp-validation-for="author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="number" class="control-label"></label>
                <input asp-for="number" class="form-control" />
                <span asp-validation-for="number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

final_pro/Views/Postbooks/Delete.cshtml
@model final_pro.Models.Postbook

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Postbook</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.year)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="title" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

final_pro/Views/Postbooks/Details.cshtml
@model final_pro.Models.Postbook

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Postbook</h4>
    <hr />
    <dl class="row">
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.number)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.year)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.title">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

final_pro/Views/Postbooks/Edit.cshtml
@model final_pro.Models.Postbook

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Postbook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="title" />
            <div class="form-group">
                <label asp-for="author" class="control-label"></label>
                <input asp-for="author" class="form-control" />
                <span asp-validation-for="author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="number" class="control-label"></label>
                <input asp-for="number" class="form-control" />
                <span asp-validation-for="number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="year" class="control-label"></label>
                <input asp-for="year" class="form-control" />
                <span asp-validation-for="year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

final_pro/Views/Postbooks/Index.cshtml
@model IEnumerable<final_pro.Models.Postbook>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a><br />
    @using (@Html.BeginForm("Index", "Postbooks", FormMethod.Get))
    {
        <b>Search By:</b>
    <br/>
        @Html.RadioButton("searchBy", "title", true) <text>Title</text>
        @Html.RadioButton("searchBy", "author", true) <text>Author</text>
        

        <br />

        @Html.TextBox("search")
        <input type="submit" value="search" />
    }
</p>

@if (Model.Count() == 0)
{
    <tr>
        <td colspan="4">
            No records match search criteria
        </td>
    </tr>
}
else
{
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.year)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.year)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.title">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.title">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.title">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
}

final_pro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - final_pro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">final_pro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - final_pro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>